### ISSUE TITLE
No shipping estimates being displayed

### ISSUE THREAD

**Issue by MartinaEL** [Transdirect/woocommerce#1]
When I or a customer is placing an order and I choose the Transdirect shipping method and then choose the Transdirect Shipping method the 'Get A Shipping Estimate' popup comes up ok, and when I enter my postcode the autocomplete correctly shows the suburbs and I can choose one, but then it doesn't work from here.

When I choose 'Get Quote' nothing happens (although I can see when inspecting the side quotes.php is returning ok) but nothing happens.

Then if I click on the Transdirect Shipping radio button again this pop up appears?
![screen shot 2014-10-22 at 2 16 58 pm](https://cloud.githubusercontent.com/assets/3794709/4730462/457b42b4-599a-11e4-8d04-186b076f9128.png)
![screen shot 2014-10-22 at 2 16 19 pm](https://cloud.githubusercontent.com/assets/3794709/4730463/45816a54-599a-11e4-9b30-800df7afff52.png)
![screen shot 2014-10-22 at 2 15 31 pm](https://cloud.githubusercontent.com/assets/3794709/4730464/4583b912-599a-11e4-92ae-14cf5b4be002.png)

**Comment by worldwidedecor** [comment]
I am experiencing the exact same problem with the qoute not showing.

 With 2.0 the authentication works, but with 2.1 I cant even authenticate because the API key is not working. I have tried calling transdirect but no help was given. Can you please type a solution here, or we might go with Australia post.

**Comment by ellenortiz** [comment]
Hi Worldwidedecor, 

Can you download the new version 3.2 plugin.
